#include "energiathread.h"

EnergiaThread::EnergiaThread() {}
/*
this->id = id;
    this->colaEnergia = colaEnergia;
    this->queueLabel = queueLabel;
    this->timerLabel = timerLabel;
    this->tiempoSbx = tiempoSbx;
    this->capacidadSbx = capacidadSbx;
    this->corriendoChbx = corriendoChbx;
*/
void EnergiaThread::run(){
    while(true){


        int secondsLeft = this->tiempoSbx->value();
        while(secondsLeft > 0){
            if(!(this->corriendoChbx->isChecked())){
                QThread::sleep(1);
                continue;
            }
            countdownLabel->setText(QString::number(secondsLeft--));
            QThread::sleep(1);
        }
        //cuando secondsLeft llega a 0, sigue aqui.
        int randomNumber = QRandomGenerator::global()->generate();
        qDebug() << "Number generated by thread" << this->id << "is:" << randomNumber;
        if(randomNumber%3==0){
            this->colaEnergia->encolar("Energia Oscura");
        } else if (randomNumber%2 == 1){
            this->colaEnergia->encolar("Energia Cosmica");
        } else{
            this->colaEnergia->encolar("Energia Elemental");
        }

    }
}
