/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supervivenciaenlaisla2024130345;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Proyecto Diseño
 */
public class Juego extends javax.swing.JFrame {
private JPanel[][] panelesMapa; //array para almacenar las casillas en gui
	/**
	 * Creates new form Juego
	 */
	public Juego() {
		initComponents();
		Mapa mapaTablero = new Mapa(26,26);
		inicializarMapaGraficamente(mapaTablero);
		RefrescarMapaThread refrescarMapaThread = new RefrescarMapaThread(mapaTablero,panelesMapa,jPanel1);
		refrescarMapaThread.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new java.awt.GridLayout(26, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	private void inicializarMapaGraficamente(Mapa mapa) {
        panelesMapa = new JPanel[mapa.getMapa().length][mapa.getMapa()[0].length];
		
		//Poner un 4x4 de casillas ya descubiertas en el centro.
		int centroFila = mapa.getMapa().length / 2;
		int centroColumna = mapa.getMapa()[0].length / 2;
		for (int fila = centroFila - 2; fila <= centroFila + 1; fila++) {
			for (int columna = centroColumna - 2; columna <= centroColumna + 1; columna++) {
				mapa.getCasilla(fila, columna).setDescubierta(true);
			}
		} 
		
        for (int fila = 0; fila < mapa.getMapa().length; fila++) {
            for (int columna = 0; columna < mapa.getMapa()[0].length; columna++) {
                JPanel panelCasilla = new JPanel();
                panelCasilla.setBorder(BorderFactory.createLineBorder(Color.black));
                panelCasilla.setBackground(Color.decode("#369649"));

                final int f = fila;
                final int c = columna;

                
				
                panelCasilla.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        int x = evt.getX();
                        int y = evt.getY();
						Casilla casilla = mapa.getCasilla(f, c);
						casilla.setDescubierta(true);
                        System.out.println("Casilla: (" + f + ", " + c + ")");
                        System.out.println("Coordenadas dentro del JPanel: (" + x + ", " + y + ")");
						panelCasilla.setPreferredSize(new java.awt.Dimension(32, 32));
						panelCasilla.setMinimumSize(new java.awt.Dimension(32, 32));
						panelCasilla.setMaximumSize(new java.awt.Dimension(32, 32));
						int width = panelCasilla.getWidth(); 
						int height = panelCasilla.getHeight();
						System.out.println("Dimensiones de la casilla: " + width + "x" + height + " píxeles");
						
                    }
                });

                // Añadir el panel a la matriz de paneles
                panelesMapa[fila][columna] = panelCasilla;

                // Añadir la casilla al contenedor principal
                this.jPanel1.add(panelCasilla);
            }
        }
        this.jPanel1.revalidate(); //necesarios para actualizar cambios cuando se usa grid layout
        this.jPanel1.repaint();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
